from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from dfir_conqr import __version__


def write_json_report(results: list[dict[str, Any]], case_meta: dict[str, Any], output_dir: Path) -> Path:
    payload = {
        "tool_version": __version__,
        "case": case_meta,
        "results": results,
    }
    path = output_dir / "triage_report.json"
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    return path


def write_html_report(results: list[dict[str, Any]], case_meta: dict[str, Any], output_dir: Path) -> Path:
    sections = []
    for r in results:
        status_class = {
            "success": "ok", "partial": "warn", "error": "err", "skipped": "skip",
        }.get(r["status"], "")
        body = html.escape(json.dumps(r["data"], indent=2, default=str))
        artifacts = "".join(f"<li>{html.escape(a)}</li>" for a in r.get("artifact_files", []))
        error_block = (
            f"<pre class='error'>{html.escape(r['error'])}</pre>" if r.get("error") else ""
        )
        sections.append(f"""
        <section class="collector {status_class}">
          <h2>{html.escape(r['name'])} <span class="badge">{html.escape(r['status'])}</span></h2>
          <p class="meta">duration: {r.get('duration_seconds')}s</p>
          {error_block}
          {"<h3>Artifacts</h3><ul>" + artifacts + "</ul>" if artifacts else ""}
          <details><summary>Raw data</summary><pre>{body}</pre></details>
        </section>
        """)

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DFIR-CONQR Triage Report - {html.escape(case_meta.get('case_id', ''))}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; background:#0f1115; color:#e6e6e6; }}
  h1 {{ font-size: 1.5rem; }}
  .meta-box {{ background:#181b22; padding:1rem; border-radius:8px; margin-bottom:1.5rem; }}
  section.collector {{ background:#181b22; border-radius:8px; padding:1rem 1.5rem; margin-bottom:1rem; border-left:4px solid #444; }}
  section.ok {{ border-left-color:#2ecc71; }}
  section.warn {{ border-left-color:#f1c40f; }}
  section.err {{ border-left-color:#e74c3c; }}
  section.skip {{ border-left-color:#7f8c8d; }}
  .badge {{ font-size:0.7rem; text-transform:uppercase; opacity:0.7; margin-left:0.5rem; }}
  pre {{ background:#0b0d11; padding:0.75rem; border-radius:6px; overflow-x:auto; max-height:400px; }}
  pre.error {{ color:#ff8080; }}
  .meta {{ opacity:0.6; font-size:0.85rem; }}
</style>
</head>
<body>
  <h1>DFIR-CONQR Triage Report</h1>
  <div class="meta-box">
    <div><b>Case ID:</b> {html.escape(str(case_meta.get('case_id','')))}</div>
    <div><b>Examiner:</b> {html.escape(str(case_meta.get('examiner','')))}</div>
    <div><b>Generated by:</b> DFIR-CONQR v{__version__}</div>
  </div>
  {''.join(sections)}
</body>
</html>"""

    path = output_dir / "triage_report.html"
    path.write_text(html_doc, encoding="utf-8")
    return path
